Feature/ehj1 iv 14
infoshareacademy/ehj1-iVesta pull request #3
Opened 2022-03-16 14:20 UTC by MateuszPaszkiewicz88

Add logger to project.

2022-03-16 14:26 UTC, itdrist requested changes

2022-03-16 14:26 UTC, itdrist commented on pom.xml
> +    </dependencies>
A gdzie Slf4J?

2022-03-16 14:26 UTC, itdrist commented on src/main/java/Main.java
> +import org.apache.log4j.Logger;
lepiej slf4j

2022-03-16 14:26 UTC, itdrist commented on src/main/resources/log4j.properties
> +# Redirect log messages to console
loguj też do plików

2022-03-23 10:37 UTC, kroskowski-d approved these changes

2022-03-23 13:04 UTC, itdrist approved these changes

2022-03-23 13:04 UTC, itdrist commented on pom.xml
> +    </dependencies>
slf4j-nop będzie to wysyłał w niebyt, czyli logi się nigdzie za zapiszą... to słabe...

2022-03-23 13:04 UTC, itdrist commented on src/main/resources/log4j2.xml
> +        <Property name="LOG_PATTERN">%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} - %m%n</Property>
tego nie używasz...

2022-03-23 13:50 UTC, itdrist requested changes
logów nie wrzucć do repo

2022-03-23 13:54 UTC, itdrist approved these changes

2022-03-23 13:55 UTC, merged