Feature/ehj1 iv 15
infoshareacademy/ehj1-iVesta pull request #4
Opened 2022-03-16 14:28 UTC by arkadiusz-iwaniuk

2022-03-16 14:33 UTC, polomi1 commented
chyba nie wszystkie zależności są potrzebne

2022-03-16 14:41 UTC, itdrist requested changes

2022-03-16 14:41 UTC, itdrist commented on pom.xml
> +            <groupId>com.opencsv</groupId>
nie wrzucaj wszystkich zależności, jakie Ci się nawiną. tylko te, których używasz...

2022-03-16 14:41 UTC, itdrist commented on pom.xml
> +            <version>3.22.0</version>
assertj na scope test

2022-03-16 14:41 UTC, itdrist commented on pom.xml
> +            <groupId>org.apache.maven.surefire</groupId>
po co to? wygląda na zbędne

2022-03-16 14:41 UTC, itdrist commented on pom.xml
> +            <groupId>org.jetbrains.kotlin</groupId>
zmieniasz język z Javy na Kotlina?

2022-03-16 15:31 UTC, kroskowski-d approved these changes

2022-03-17 08:32 UTC, polomi1 approved these changes
teraz ok

2022-03-23 08:20 UTC, itdrist commented on pom.xml
> +            <version>3.22.0</version>
dziękuję za zmiany

2022-03-23 08:21 UTC, itdrist commented on pom.xml
> +            <groupId>org.jetbrains.kotlin</groupId>
wciąż niepotrzebne

2022-03-23 11:25 UTC, itdrist approved these changes

2022-03-23 11:26 UTC, merged