Feature/ehj1 iv 20
infoshareacademy/ehj1-iVesta pull request #6
Opened 2022-03-20 14:57 UTC by polomi1

ehj1 iv 20: klasy service'owe oraz struktura menu

Stworzyłem te klasy oraz wstępne manu ale mam wątpliwości czy to o to chodziło. Więc wszystkie sugestie mile widziane.

2022-03-21 17:57 UTC, kroskowski-d commented on src/main/java/Services/MenuService.java
> +        if (item == 1) {
Zamieniłbym tego ifa na swicha. Pewnie dojdą jakieś kolejne opcje więc switch będzie czytelniejszy

2022-03-21 18:15 UTC, kroskowski-d requested changes
If do podmiany na switcha a reszta według mnie jest w porządku

2022-03-21 19:25 UTC, kroskowski-d approved these changes

2022-03-22 06:07 UTC, k-dudziak approved these changes
Ok

2022-03-22 08:54 UTC, merged